# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#global settings
title: Site Title #ourUhk ‧ 我們IU香港後援會
email: ouruhk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ourUhk ‧ 我們IU香港後援會
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kennethive.github.io/jeykll_blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  kennethive

#social medio links
facebook_url: https://facebook.com
instagram_url: https://instagram.com
mewe_url: https://mewe.com
youtube_url: https://youtube.com
twitter_url: https://twitter.com

#assets
header-background: https://yt3.ggpht.com/wFiXi-rTNhwRaOaMH-ApslRGW9V2uIVs-PyA9UbtOvx3wXugFzAajgTOxCgE5Dk9L03dzhEjdw=w1060-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
